import type { ArchInputPackage, ClassifiedRequirement } from '../../api/specweaver';

function sanitizeLine(value: string): string {
  return value.replace(/\r?\n/g, ' ').trim();
}

function markdownEscape(value: string): string {
  return value.replace(/([\\`*_{}[\]()#+\-.!|>])/g, '\\$1');
}

function sectionTitleFromCategory(category: string): string {
  return category
    .split('_')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}

function formatRequirementMarkdown(requirement: ClassifiedRequirement): string {
  const lines: string[] = [
    `- **${markdownEscape(requirement.requirementId)}** (${markdownEscape(requirement.type)})`,
    `  - Statement: ${markdownEscape(sanitizeLine(requirement.statement))}`,
    `  - Confidence: ${markdownEscape(requirement.confidence)}${requirement.isInferred ? ' (inferred)' : ''}`,
  ];

  if (requirement.inferenceReasoning) {
    lines.push(`  - Inference reasoning: ${markdownEscape(sanitizeLine(requirement.inferenceReasoning))}`);
  }

  if (requirement.ambiguities.length > 0) {
    lines.push(`  - Ambiguities: ${requirement.ambiguities.map((value) => markdownEscape(sanitizeLine(value))).join('; ')}`);
  }

  if (requirement.sourceDocumentIds.length > 0) {
    lines.push(`  - Source documents: ${requirement.sourceDocumentIds.map((value) => markdownEscape(value)).join(', ')}`);
  }

  if (requirement.sourceExcerpts.length > 0) {
    lines.push('  - Source excerpts:');
    requirement.sourceExcerpts.forEach((excerpt) => {
      lines.push(`    - ${markdownEscape(sanitizeLine(excerpt))}`);
    });
  }

  return lines.join('\n');
}

function formatRequirementText(requirement: ClassifiedRequirement): string {
  const lines: string[] = [
    `${requirement.requirementId} (${requirement.type})`,
    `Statement: ${sanitizeLine(requirement.statement)}`,
    `Confidence: ${requirement.confidence}${requirement.isInferred ? ' (inferred)' : ''}`,
  ];

  if (requirement.inferenceReasoning) {
    lines.push(`Inference reasoning: ${sanitizeLine(requirement.inferenceReasoning)}`);
  }

  if (requirement.ambiguities.length > 0) {
    lines.push(`Ambiguities: ${requirement.ambiguities.map(sanitizeLine).join('; ')}`);
  }

  if (requirement.sourceDocumentIds.length > 0) {
    lines.push(`Source documents: ${requirement.sourceDocumentIds.join(', ')}`);
  }

  if (requirement.sourceExcerpts.length > 0) {
    lines.push('Source excerpts:');
    requirement.sourceExcerpts.forEach((excerpt, index) => {
      lines.push(`  ${index + 1}. ${sanitizeLine(excerpt)}`);
    });
  }

  return lines.join('\n');
}

function groupedRequirements(pkg: ArchInputPackage): Map<string, ClassifiedRequirement[]> {
  const groups = new Map<string, ClassifiedRequirement[]>();
  pkg.requirements.forEach((requirement) => {
    const existing = groups.get(requirement.category);
    if (existing) {
      existing.push(requirement);
      return;
    }
    groups.set(requirement.category, [requirement]);
  });
  return groups;
}

/**
 * Build a human-readable Markdown document for an ArchInputPackage export.
 *
 * @param pkg Package payload generated by SpecWeaver.
 * @returns Markdown document content.
 */
export function buildPackageMarkdown(pkg: ArchInputPackage): string {
  const lines: string[] = [
    '# SpecWeaver Package Export',
    '',
    `- Package ID: ${pkg.packageId}`,
    `- Session ID: ${pkg.sessionId}`,
    `- Created At: ${pkg.createdAt}`,
    `- Readiness Score: ${pkg.readinessScore}`,
    `- Total Requirements: ${pkg.totalRequirements}`,
    `- High Confidence Count: ${pkg.highConfidenceCount}`,
    `- Inferred Count: ${pkg.inferredCount}`,
    '',
    '## System Description',
    '',
    pkg.systemDescription || 'No system description provided.',
    '',
    '## Requirements',
    '',
  ];

  const groups = groupedRequirements(pkg);
  if (groups.size === 0) {
    lines.push('No requirements found.', '');
  } else {
    groups.forEach((requirements, category) => {
      lines.push(`### ${sectionTitleFromCategory(category)}`, '');
      requirements.forEach((requirement) => {
        lines.push(formatRequirementMarkdown(requirement), '');
      });
    });
  }

  lines.push('## Gaps', '');
  if (pkg.gaps.length === 0) {
    lines.push('No gaps identified.', '');
  } else {
    pkg.gaps.forEach((gap) => {
      lines.push(
        `- **${markdownEscape(sanitizeLine(gap.area))}** [${markdownEscape(sanitizeLine(gap.severity))}]`,
        `  - Explanation: ${markdownEscape(sanitizeLine(gap.explanation))}`,
        `  - Clarification question: ${markdownEscape(sanitizeLine(gap.clarificationQuestion))}`,
        '',
      );
    });
  }

  lines.push('## Conflicts', '');
  if (pkg.conflicts.length === 0) {
    lines.push('No conflicts identified.', '');
  } else {
    pkg.conflicts.forEach((conflict, index) => {
      lines.push(`- Conflict ${index + 1}`, `  - Requirement IDs: ${conflict.requirementIds.join(', ')}`);
      lines.push(`  - Description: ${markdownEscape(sanitizeLine(conflict.description))}`);
      if (conflict.interpretations.length > 0) {
        lines.push(
          `  - Interpretations: ${conflict.interpretations
            .map((value) => markdownEscape(sanitizeLine(value)))
            .join('; ')}`,
        );
      }
      lines.push(`  - Clarification question: ${markdownEscape(sanitizeLine(conflict.clarificationQuestion))}`, '');
    });
  }

  lines.push('## Source Documents', '');
  if (pkg.sourceDocuments.length === 0) {
    lines.push('No source documents listed.');
  } else {
    pkg.sourceDocuments.forEach((document, index) => {
      const displayId = document.id ?? document.documentId ?? `document-${index + 1}`;
      lines.push(
        `- ${markdownEscape(String(displayId))}`,
        `  - Filename: ${markdownEscape(document.filename ?? 'n/a')}`,
        `  - Source Label: ${markdownEscape(document.sourceLabel ?? 'n/a')}`,
        `  - Type: ${markdownEscape(String(document.documentType ?? 'n/a'))}`,
      );
    });
  }

  return lines.join('\n');
}

/**
 * Build a plain text export for an ArchInputPackage.
 *
 * @param pkg Package payload generated by SpecWeaver.
 * @returns Plain text document content.
 */
export function buildPackageText(pkg: ArchInputPackage): string {
  const lines: string[] = [
    'SpecWeaver Package Export',
    '=========================',
    '',
    `Package ID: ${pkg.packageId}`,
    `Session ID: ${pkg.sessionId}`,
    `Created At: ${pkg.createdAt}`,
    `Readiness Score: ${pkg.readinessScore}`,
    `Total Requirements: ${pkg.totalRequirements}`,
    `High Confidence Count: ${pkg.highConfidenceCount}`,
    `Inferred Count: ${pkg.inferredCount}`,
    '',
    'System Description',
    '------------------',
    pkg.systemDescription || 'No system description provided.',
    '',
    'Requirements',
    '------------',
  ];

  const groups = groupedRequirements(pkg);
  if (groups.size === 0) {
    lines.push('No requirements found.', '');
  } else {
    groups.forEach((requirements, category) => {
      lines.push(sectionTitleFromCategory(category), ''.padEnd(sectionTitleFromCategory(category).length, '~'));
      requirements.forEach((requirement) => {
        lines.push(formatRequirementText(requirement), '');
      });
    });
  }

  lines.push('Gaps', '----');
  if (pkg.gaps.length === 0) {
    lines.push('No gaps identified.', '');
  } else {
    pkg.gaps.forEach((gap, index) => {
      lines.push(
        `${index + 1}. ${sanitizeLine(gap.area)} [${sanitizeLine(gap.severity)}]`,
        `   Explanation: ${sanitizeLine(gap.explanation)}`,
        `   Clarification question: ${sanitizeLine(gap.clarificationQuestion)}`,
      );
    });
    lines.push('');
  }

  lines.push('Conflicts', '---------');
  if (pkg.conflicts.length === 0) {
    lines.push('No conflicts identified.', '');
  } else {
    pkg.conflicts.forEach((conflict, index) => {
      lines.push(
        `${index + 1}. Requirement IDs: ${conflict.requirementIds.join(', ')}`,
        `   Description: ${sanitizeLine(conflict.description)}`,
      );
      if (conflict.interpretations.length > 0) {
        lines.push(`   Interpretations: ${conflict.interpretations.map(sanitizeLine).join('; ')}`);
      }
      lines.push(`   Clarification question: ${sanitizeLine(conflict.clarificationQuestion)}`);
    });
    lines.push('');
  }

  lines.push('Source Documents', '----------------');
  if (pkg.sourceDocuments.length === 0) {
    lines.push('No source documents listed.');
  } else {
    pkg.sourceDocuments.forEach((document, index) => {
      const displayId = document.id ?? document.documentId ?? `document-${index + 1}`;
      lines.push(
        `${index + 1}. ${displayId}`,
        `   Filename: ${document.filename ?? 'n/a'}`,
        `   Source Label: ${document.sourceLabel ?? 'n/a'}`,
        `   Type: ${String(document.documentType ?? 'n/a')}`,
      );
    });
  }

  return lines.join('\n');
}

/**
 * Trigger a browser download for a package export.
 *
 * @param pkg Package payload generated by SpecWeaver.
 * @param format Export format requested by the user.
 */
export function downloadPackageExport(pkg: ArchInputPackage, format: 'markdown' | 'text'): void {
  const nowStamp = new Date().toISOString().replace(/[:.]/g, '-');
  const extension = format === 'markdown' ? 'md' : 'txt';
  const mimeType = format === 'markdown' ? 'text/markdown;charset=utf-8' : 'text/plain;charset=utf-8';
  const fileBase = `specweaver-${pkg.sessionId}-${nowStamp}`;
  const content = format === 'markdown' ? buildPackageMarkdown(pkg) : buildPackageText(pkg);

  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${fileBase}.${extension}`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
