package com.archon.api.controller;

import com.archon.api.dto.ChatRequest;
import com.archon.api.dto.AgentResponse;
import com.archon.api.service.ChatService;
import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.MediaType;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;

import java.io.IOException;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.ScheduledFuture;
import java.util.concurrent.TimeUnit;

/**
 * REST controller for handling real-time chat streaming operations.
 * 
 * Provides endpoints for streaming chat messages to clients using Server-Sent
 * Events (SSE).
 * All endpoints are prefixed with "/api/v1/chat" and require authentication.
 */
@RestController
@RequestMapping("/api/v1/chat")
@RequiredArgsConstructor
@Slf4j
public class ChatController {

    private final ChatService chatService;
    private final ObjectMapper objectMapper;

    private static final long SSE_TIMEOUT_MS = 600_000L;
    // 600 seconds — accommodates re-iteration runs with keepalive.

    private static final long HEARTBEAT_INTERVAL_SECONDS = 15L;
    // Prevents proxy idle timeout during long-running stages.

    /**
     * Streams chat responses to the client in real-time using Server-Sent Events.
     * 
     * This endpoint establishes a persistent connection with the client and sends chat
     * responses as they are generated by the chat service. The connection has a timeout
     * of 3 minutes (180,000ms).
     * 
     * @param request the {@link ChatRequest} containing conversation ID, mode, and other
     *                chat parameters. Must be valid and not null.
     * @param userId the authenticated user's ID extracted from the security principal.
     *               User must be authenticated to access this endpoint.
     * 
     * @return {@link SseEmitter} configured to send streamed chat responses as JSON events.
     *         The emitter will send response events as they are published by the chat service.
     *         On error, the emitter will be completed with an error. On successful completion,
     *         the emitter will send a completion event.
     * 
     * @throws IOException if an I/O error occurs while sending events through the emitter.
     * 
     * HTTP Details:
     * - Method: POST
     * - Content-Type: application/x-www-form-urlencoded or application/json
     * - Produces: text/event-stream
     * - Authentication: Required (@AuthenticationPrincipal)
     * 
     * Example Response Events:
     * Responses are sent as JSON-formatted SSE events, allowing real-time chat message streaming.
     */
    @PostMapping(value = "/stream", produces = MediaType.TEXT_EVENT_STREAM_VALUE)
    public SseEmitter streamChat(
            @RequestBody @Valid ChatRequest request,
            @AuthenticationPrincipal String userId) {

        log.info("Streaming chat for conversation: {}, mode: {}, user: {}",
                request.getConversationId(), request.getMode(), userId);

        SseEmitter emitter = new SseEmitter(SSE_TIMEOUT_MS);

        ScheduledExecutorService heartbeatExecutor =
                Executors.newSingleThreadScheduledExecutor(r -> {
                    Thread t = new Thread(r, "sse-heartbeat");
                    t.setDaemon(true);
                    return t;
                });
        ScheduledFuture<?> heartbeatFuture = heartbeatExecutor.scheduleAtFixedRate(() -> {
            try {
                emitter.send(SseEmitter.event().comment(" heartbeat"));
            } catch (IOException e) {
                // If we can't write, the connection is likely closed already.
                emitter.complete();
            }
        }, HEARTBEAT_INTERVAL_SECONDS, HEARTBEAT_INTERVAL_SECONDS, TimeUnit.SECONDS);

        Runnable stopHeartbeat = () -> {
            heartbeatFuture.cancel(true);
            heartbeatExecutor.shutdownNow();
        };
        emitter.onCompletion(stopHeartbeat);
        emitter.onTimeout(stopHeartbeat);
        emitter.onError(e -> stopHeartbeat.run());

        chatService.streamChat(request, userId).subscribe((AgentResponse response) -> {
            try {
                emitter.send(SseEmitter.event()
                        .data(objectMapper.writeValueAsString(response),
                                MediaType.APPLICATION_JSON));
            } catch (IOException e) {
                emitter.completeWithError(e);
            }
        }, emitter::completeWithError, emitter::complete);

        return emitter;
    }
}