package com.specweaver.api.repository;

import com.specweaver.api.domain.model.GeneratedPackage;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.Optional;
import java.util.UUID;

/**
 * Repository for ArchInputPackages generated by SpecWeaver.
 */
public interface GeneratedPackageRepository extends JpaRepository<GeneratedPackage, UUID> {

    Optional<GeneratedPackage> findBySessionId(UUID sessionId);
}
