package com.archon.api.domain.model;
/**
 * Enum representing the role of a message in a conversation.
 * 
 * This enum defines the different types of participants or sources
 * that can send messages within the AI assistant system.
 */
public enum MessageRole {
    /**
     * Represents a message sent by the end user.
     * This role indicates content originating from the user interacting with the system.
     */
    USER,
    
    /**
     * Represents a message sent by the AI assistant.
     * This role indicates responses or content generated by the AI system.
     */
    ASSISTANT,
    
    /**
     * Represents the result or output from a tool execution.
     * This role indicates content that is the result of a tool invocation or external service call.
     */
    TOOL_RESULT
}
